language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install: "python setup.py install"
script:
  - cd tests
  - python manage.py test
env:
  - NEO4J_VERSION="3.5"
  - NEO4J_VERSION="4.0"
  - NEO4J_VERSION="4.1"
before_install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - sleep 10
